# ------------------------------------------------------------------------------
# INCLUDE, EXCLUDE & IGNORED PATHS
# ------------------------------------------------------------------------------

# paths to include during linting.
included:
    - Shoestock

# paths to ignore during linting.
excluded:
    - Carthage
    - Pods

# ------------------------------------------------------------------------------
# EXCLUDE & IGNORED RULES
# ------------------------------------------------------------------------------

# rule identifiers to exclude from running
disabled_rules:
    - trailing_whitespace
    - large_tuple
    - missing_docs
    - cyclomatic_complexity
    - type_body_length
    - identifier_name
    - for_where
    - class_delegate_protocol
    - private_over_fileprivate
opt_in_rules: # some rules are only opt-in
    - switch_case_alignment
    - overridden_super_call
    - closure_spacing
    - closure_end_indentation
    - redundant_nil_coalescing
    - operator_usage_whitespace
    - explicit_init
    - vertical_parameter_alignment_on_call
    - conditional_returns_on_newline
    # Find all the available rules by running:
    # swiftlint rules

# ------------------------------------------------------------------------------
# LENGHT RULES
# ------------------------------------------------------------------------------

# file
file_length:
    warning: 700 # lenght considered warning
    error: 1200  # lenght considered error

# type body
type_body_length:
    - 400 # lenght considered warning
    - 500  # lenght considered error

# code line
line_length: 500

# ------------------------------------------------------------------------------
# FORCE RULES
# ------------------------------------------------------------------------------

# force
force_cast: warning
force_try: warning

# ------------------------------------------------------------------------------
# NAMING RULES
# ------------------------------------------------------------------------------

# type name
type_name:
    min_length: 3
    max_length:
        warning: 50
    excluded:
        - iPhone
        - SKU
        - PDP

# variable name
variable_name:
    min_length: 3
    max_length:
        warning: 50
    excluded:
        - id
        - URL
        - url
        - GlobalAPIKey
        - sku
        - map
        - key
        - red
        - rhs
        - lhs
        - PDP
        - pi

# ------------------------------------------------------------------------------
# CUSTOM RULES
# ------------------------------------------------------------------------------

custom_rules:

    # Style Guide
    sg_nil_verification:
        name: "SG nil verification"
        regex: "(!=[ ]*nil[ ]*[{][ ]*[}]|==[ ]*nil[ ]*[{][ ]*[}])"
        message: "Avoid use != nil {} or == nil {}. Example: instead of using 'param != nil {} else', use 'param == nil'" 
        severity: warning

    # Style Guide
    default_strings:
        name: "Avoid default strings"
        regex: "(shoestock|cruzeiro|shopcruzeiro|lojadointer|internacional|cazadosport|santos|santosstore|chivas|tiendachivas|palmeiras|mundopalmeiras|soycuervo|zattini|netshoes)"
        excluded: ".*Environment.swift" # regex that defines paths to exclude during linting. optional
        match_kinds: 
            - string
        message: "Avoid default strings in code. Use the Environment struct to access stores values as name, siteUrl, storeURL. Example: let screenTitle = Inject.environment.store instead of let screenTitle = 'shoestock' " 
        severity: warning

    # Style Guide
    is_not_empty_rule:
        name: "Not empty verification SG"
        regex: "([.]count|[.]length[(][)] )[ ]*>[ ]*0"
        message: "Use IsNotEmpty instead of count > 0"
        severity: warning

    # Style Guide
    isEmpty_rule:
        name: "Empty verification SG"
        regex: "([.]count|[.]length[(][)] )[ ]*==[ ]*0"
        message: "Use isEmpty instead of count == 0"
        severity: warning

    # Local Storage hierarchy
    local_storage_rule:
        name: "Local Storage hierarchy"
        regex: "[a-z]*Persister[(][)]"
        excluded: "(.*Storage.swift|.*Persister.swift)" # regex that defines paths to exclude during linting. optional
        message: "Local Storage"
        severity: warning

    # Use to avoid unnecessary inheritance
    viewModel_unnecessary_inheritance:
        name: "ViewModel Inheritance "
        regex: "ViewModel[ ]*:[ ]*NSObject"
        message: "ViewModel unnecessary inheritance"
        severity: warning

    # Use localized before to upperCase or lowerCase a String
    localized_rule:
        name: "Localized rule"
        regex: "cased[(][])].localized"
        message: "Use localized before to upperCase or lowerCase a String"
        severity: warning

    # Use colors from ThemeColors enum instead of create an UIColor
    theme_color:
        name: "Theme Color"
        regex: "(UIColor[.,(hexString:)])"
        match_kinds: identifier
        message: "Use the colors from ThemeColors enum"
        severity: warning

    # Use images from Asset enum instead of create an UIImage
    image_asset:
        name: "Theme Asset"
        regex: "named:"
        message: "Use the images from Asset enum"
        severity: warning

# ------------------------------------------------------------------------------
# REPORTER TYPE (xcode, json, csv, checkstyle, junit, html, emoji)
# ------------------------------------------------------------------------------

reporter: "xcode"